# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      - name: Compile website into HTML
        run: npx agregore-markdown-site-generator
      - name: Publish to Distributed Press
        uses: hyphacoop/actions-distributed-press@v1.1.0
        with:
          publish_dir: ./
          dp_url: https://press.mauve.moe
          refresh_token: ${{ secrets.DISTRIBUTED_PRESS_TOKEN }}
          site_url: agregore.mauve.moe
